const fs = require('fs')
const p = 'src/App.tsx'
const a = fs.readFileSync(p, 'utf8').split(/\r?\n/)
const set = (n, v) => { a[n - 1] = v }
set(487, `         <section className="challenge-copy"><span>FIVE SYSTEM BREAKPOINTS</span><h2>触觉为什么<br/><em>仍然难以可靠行动？</em></h2><p>问题不在某一个指标，而在硬件、数据、模型和任务评价尚未形成稳定闭环。</p><div className="challenge-list">{(Object.keys(items) as ChallengeKey[]).map(key => <button key={key} className={active === key ? 'active' : ''} onClick={() => setActive(key)} aria-pressed={active === key}><span>{items[key].n}</span><strong>{items[key].label}</strong><small>{items[key].en}</small><i>→</i></button>)}</div><div className="challenge-note"><i/>点击断点，查看失效表现、根因与应报告指标。</div></section>`)
set(524, `         <section className="task-value-copy"><span>TACTILE VALUE IN TASKS</span><h2>触觉不只是<br/><em>识别更多</em></h2><p>它把接触后的物理后果变成行动依据，形成“观测—动作—再观测”的具身闭环。</p><div className="value-function-tabs">{(Object.keys(data) as TaskValueKey[]).map(key => <button key={key} className={active === key ? 'active' : ''} onClick={() => { setActive(key); setSelectedTask(data[key].tasks[0].label) }} aria-pressed={active === key}><span>{data[key].n}</span><strong>{data[key].label}</strong><small>{data[key].en}</small></button>)}</div><div className="task-value-note"><i/>点击功能标签，再点击右侧任务标签展开任务细节。</div></section>`)
set(552, `         <g className="local-center node-card"><rect x="485" y="341" width="178" height="98" rx="15"/><circle cx="518" cy="375" r="12"/><text className="node-kicker" x="546" y="372">FAST LOCAL CENTER</text><text className="node-title" x="514" y="409">快速局部中枢</text></g>`)
set(554, `         <g className="encoding node-card"><rect x="475" y="105" width="178" height="98" rx="15"/><circle cx="508" cy="139" r="12"/><text className="node-kicker" x="536" y="136">AFFERENT PATH</text><text className="node-title" x="504" y="173">传入与编码</text></g>`)
set(555, `         <g className="output node-card"><rect x="734" y="354" width="198" height="104" rx="15"/><circle cx="769" cy="389" r="12"/><text className="node-kicker" x="797" y="386">ACTION / OUTPUT</text><text className="node-title" x="764" y="423">执行与触觉输出</text></g>`)
set(574, `     slip: { en: '01 / FAST REFLEX', title: '滑移：先反射，再解释', lead: '高频变化沿短通路触发抓力修正；高层模型随后更新对象与任务状态。', points: ['端侧检测初触、冲击、滑移与过载', '最坏响应时间比平均推理速度更关键'] },`)
set(575, `     explore: { en: '02 / ACTIVE TOUCH', title: '未知物体：主动获得证据', lead: '世界模型比较候选接触后果，选择信息收益更高且风险可控的下一次触碰。', points: ['动作条件建模区分物体属性与探索方式', '联合优化信息增益、任务进展与损伤风险'] },`)
set(576, `     human: { en: '03 / SOCIAL TOUCH', title: '人机接触：双向而有边界', lead: '系统既理解人的接触状态，也以力、振动或形变回应；同意与退出不是附加项。', points: ['先保证物理安全与行为可预测', '持续同意、个体适应和可撤回机制'] },`)
set(552, a[551].replace('</g>', '</g>'))
set(689, `         <desc id="future-figure-desc">二维侧面人物通过手指接触柔性表面，脑、脊髓、手和环境由感觉上行、快速反射与控制下行连接。</desc>`)
set(779, `       <button type="button" className="future-hotspot hotspot-spine" aria-label="查看脊髓：低时延局部闭环" aria-pressed={focus === 'spine'} aria-controls="future-detail" onClick={() => activate('spine')}><i/><span>脊髓</span></button>`)
set(780, `       <button type="button" className="future-hotspot hotspot-hand" aria-label="查看手：感受与执行共体" aria-pressed={focus === 'hand'} aria-controls="future-detail" onClick={() => activate('hand')}><i/><span>手</span></button>`)
set(781, `       <button type="button" className="future-hotspot hotspot-contact" aria-label="查看接触：环境进入系统" aria-pressed={focus === 'contact'} aria-controls="future-detail" onClick={() => activate('contact')}><i/><span>接触</span></button>`)
set(831, `           <span className="sr-only" aria-live="polite">当前显示：{current.title}{playing ? '，正在播放感知与控制闭环' : ''}</span>`)
set(847, `     ['共形', '适配尺寸、曲率与局部刚度'],`)
set(848, `     ['可变形', '随拉伸、弯曲和运动保持标定'],`)
set(849, `     ['泛在部署', '从指尖扩展到手、足、臂与躯干'],`)
set(850, `     ['可维护', '局部更换、自修复与安全降级'],`)
set(853, `     ['精密装配', '位置 / 力误差 / 卡阻提前量'],`)
set(854, `     ['高速抓取', '滑移提前量 / 端到端响应'],`)
set(891, `     ['材料响应', '接触先变成可测信号'],`)
set(892, `     ['采样 / 读出', '阵列扫描与前端转换'],`)
set(895, `     ['执行器响应', '产生有效力变化'],`)
set(947, `       points: ['信号层：图像、阵列、事件流、力 / 力矩与本体状态', '时间层：稳定接触、瞬态变化与动作历史', '空间—物理层：身体位置、接触坐标、压力、剪切、滑移与材料属性'],`)
set(953, `       points: ['动作条件潜在动力学：动作 → 接触事件 → 力学后果', '视觉—触觉联合生成与触觉图演化，覆盖遮挡下的物体持续性', '评价重点转向接触事件、物理一致性与不确定性，而非只看画面逼真度'],`)
set(959, `       points: ['高层：视觉—语言模型理解目标并规划长程任务', '中层：触觉世界模型比较候选动作与短期接触后果', '低层：端侧策略依据真实滑移、冲击与过载快速修正'],`)
set(1005, `       points: ['低频通路保持持续压力与形变，高频 / 事件通路捕捉冲击、纹理和滑移先兆', '用事件流、帧、振动和状态估计共同构成时空接触图', '评价变化检测提前量、事件漏检、静默期信息损失与时间对齐延迟'],`)
set(1011, `       points: ['根据不确定性选择接触位置、方向、力、速度和停止时机', '以信息增益、任务进展、能耗和损伤风险共同约束探索动作', '世界模型先预测不同动作可能产生的触觉分布，再选择风险可控动作'],`)
set(1077, `  const shortcuts = [['← / →', '切换屏幕'], ['Space', '下一页'], ['T', '切换视觉主题'], ['E', '证据与来源'], ['F', '全屏'], ['H / Esc', '帮助 / 关闭']]`)
fs.writeFileSync(p, a.join('\n'), 'utf8')
